[package]
name = "game-sudoku"
version.workspace = true
edition.workspace = true
license.workspace = true
authors.workspace = true

[dependencies]
game-core = { path = "../game-core" }
game-save = { path = "../game-save" }
game-ui-term = { path = "../game-ui-term" }
